from fastapi import APIRouter, HTTPException, Depends
from fastapi.responses import Response
from app.auth.dependencies import get_current_user
from app.database import get_supabase_admin
from datetime import datetime

router = APIRouter(prefix="/api/reports", tags=["Reports"])


def _generate_pdf_html(diagnosis: dict, user: dict) -> str:
    """Generate HTML content for PDF report."""
    result_status = diagnosis.get("status", "N/A")
    cancer_type = diagnosis.get("cancer_type", "N/A")
    risk_level = diagnosis.get("risk_level", "N/A")
    confidence = diagnosis.get("confidence_score", 0)
    explanations = diagnosis.get("ai_explanation", [])

    status_color = "#dc2626" if result_status == "detected" else "#16a34a"

    explanation_html = ""
    for note in (explanations if isinstance(explanations, list) else []):
        explanation_html += f"<li>{note}</li>"

    params_html = ""
    param_analysis = diagnosis.get("parameter_analysis", [])
    if isinstance(param_analysis, list):
        for p in param_analysis:
            if isinstance(p, dict):
                flagged = "⚠️" if p.get("flagged") else "✓"
                params_html += f"""<tr>
                    <td>{p.get('param', '')}</td>
                    <td>{p.get('value', '')}</td>
                    <td>{p.get('normal_min', '')}-{p.get('normal_max', '')} {p.get('unit', '')}</td>
                    <td>{flagged}</td>
                </tr>"""

    return f"""
    <!DOCTYPE html>
    <html>
    <head><meta charset="utf-8">
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; color: #1a1a1a; }}
        h1 {{ color: #0f5dc2; border-bottom: 2px solid #0f5dc2; padding-bottom: 10px; }}
        .header {{ display: flex; justify-content: space-between; margin-bottom: 20px; }}
        .result-box {{ background: #f0f4ff; border-left: 4px solid {status_color}; padding: 15px; margin: 20px 0; }}
        table {{ width: 100%; border-collapse: collapse; margin: 15px 0; }}
        th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
        th {{ background: #f5f5f5; }}
        .disclaimer {{ font-size: 11px; color: #888; margin-top: 30px; border-top: 1px solid #ddd; padding-top: 10px; }}
    </style>
    </head>
    <body>
        <h1>🩸 HemaAI — Blood Cancer Screening Report</h1>
        <div class="header">
            <div><strong>Patient:</strong> {user.get('name', 'N/A')}<br><strong>Email:</strong> {user.get('email', 'N/A')}</div>
            <div><strong>Date:</strong> {diagnosis.get('created_at', 'N/A')[:10]}<br><strong>Report ID:</strong> {diagnosis.get('id', 'N/A')[:8]}</div>
        </div>

        <div class="result-box">
            <h2 style="color:{status_color}; margin-top:0;">Detection Status: {result_status.upper()}</h2>
            <p><strong>Cancer Type:</strong> {cancer_type} | <strong>Risk Level:</strong> {risk_level} | <strong>Confidence:</strong> {confidence}%</p>
        </div>

        <h3>Blood Parameters</h3>
        <table>
            <tr><th>Parameter</th><th>Value</th><th>Normal Range</th><th>Status</th></tr>
            {params_html}
        </table>

        <h3>AI Clinical Notes</h3>
        <ul>{explanation_html}</ul>

        <div class="disclaimer">
            <p><strong>DISCLAIMER:</strong> This report is generated by an AI system and is not a substitute for professional medical advice.
            Always consult a qualified hematologist for diagnosis and treatment decisions.</p>
        </div>
    </body>
    </html>
    """


@router.post("/generate/{diagnosis_id}")
async def generate_report(diagnosis_id: str, user: dict = Depends(get_current_user)):
    """Generate a PDF report for a diagnosis."""
    sb = get_supabase_admin()

    # Get diagnosis
    diag_result = sb.table("diagnoses").select("*").eq("id", diagnosis_id).execute()
    if not diag_result.data:
        raise HTTPException(status_code=404, detail="Diagnosis not found")

    diagnosis = diag_result.data[0]
    if user["role"] != "admin" and diagnosis["user_id"] != user["id"]:
        raise HTTPException(status_code=403, detail="Not authorized")

    html_content = _generate_pdf_html(diagnosis, user)

    # Store report record
    report_data = {
        "user_id": user["id"],
        "diagnosis_id": diagnosis_id,
        "file_url": f"/api/reports/download/by-diagnosis/{diagnosis_id}",
    }
    sb.table("reports").insert(report_data).execute()

    return {
        "message": "Report generated",
        "report_url": f"/api/reports/download/by-diagnosis/{diagnosis_id}",
        "diagnosis_id": diagnosis_id,
    }


@router.get("/")
async def list_reports(user: dict = Depends(get_current_user)):
    """List user's reports."""
    sb = get_supabase_admin()
    result = sb.table("reports") \
        .select("*") \
        .eq("user_id", user["id"]) \
        .order("generated_at", desc=True) \
        .execute()

    return {"reports": result.data, "total": len(result.data)}


@router.get("/download/by-diagnosis/{diagnosis_id}")
async def download_report_by_diagnosis(diagnosis_id: str, user: dict = Depends(get_current_user)):
    """Download report as HTML (can be printed to PDF in browser)."""
    sb = get_supabase_admin()

    diag_result = sb.table("diagnoses").select("*").eq("id", diagnosis_id).execute()
    if not diag_result.data:
        raise HTTPException(status_code=404, detail="Diagnosis not found")

    diagnosis = diag_result.data[0]
    if user["role"] != "admin" and diagnosis["user_id"] != user["id"]:
        raise HTTPException(status_code=403, detail="Not authorized")

    html = _generate_pdf_html(diagnosis, user)

    return Response(
        content=html,
        media_type="text/html",
        headers={"Content-Disposition": f"inline; filename=hemaai_report_{diagnosis_id[:8]}.html"},
    )
